version: "3.9"
services:
  docker:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
    container_name: trybe-docker-evaluator
    network_mode: "bridge"
